[package]
name = "keen"
version = "0.3.0"
authors = ["Wu Young <doomsplayer@gmail.com>"]
description = "keen.io api v3.0 for rust"
homepage = "http://github.com/doomsplayer/keenio-rs.git"
repository = "http://github.com/doomsplayer/keenio-rs.git"
readme = "README.md"
keywords = ["keenio", "keen"]
license = "MIT"

[lib]
path = "src/lib.rs"
name = "keen"

[dependencies]
chrono = "0.2.16"
itertools = "0.4.0"
[dependencies.hyper]
version = "0.6.15"
features = ["timeouts"]
